In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#read aggregated_sleep data
df = pd.read_csv(r"C:\Users\ACER\Documents\GitHub\SDProject32\Dataset\Aggregated_Sleep.csv")
df.head()

,patient_id,window_start,mean_HR,HR_var,mean_RR,RR_var,WASO,SOL,TIB,TST,SE,snoring_counts,agitation
0,0f352,2019-06-25 18:00:00,65.039514,3.345222,11.917933,1.348875,270.0,10.0,540.0,204.0,37.777778,0.0,0.0
1,0f352,2019-06-26 18:00:00,67.176030,2.739798,11.456929,0.992935,124.0,19.0,349.0,179.0,51.289398,0.0,0.0
2,0f352,2019-06-27 18:00:00,64.623583,3.076862,11.977324,1.061488,222.0,15.0,569.0,238.0,41.827768,0.0,0.0
3,0f352,2019-06-28 18:00:00,62.416667,4.372302,11.397849,1.110011,61.0,13.0,401.0,309.0,77.057357,80.0,0.0
4,0f352,2019-06-29 12:00:00,68.082569,2.632167,13.330275,1.171064,77.0,12.0,149.0,49.0,32.885906,0.0,0.0

In [6]:
df.groupby('patient_id').describe().T

patient_id           0f352      16f4b      1fbe4      30a32       55cd4  \
mean_HR   count   7.000000  75.000000  56.000000  67.000000  101.000000
          mean   63.871361  68.679046  53.560003  64.163753   64.968206
          std     3.394559   5.724923   2.359509   3.288711    4.666326
          min    58.366667  54.222973  49.962617  57.149188   55.728155
          25%    61.905581  65.995963  51.661086  61.805034   61.316129
...                    ...        ...        ...        ...         ...
agitation min     0.000000   0.000000   0.000000   0.000000    0.000000
          25%     0.000000   0.000000   0.000000   0.000000    0.000000
          50%     0.000000   0.000000   0.000000   0.000000    0.000000
          75%     0.000000   0.000000   0.000000   0.000000    0.000000
          max     0.000000   1.000000   0.000000   0.000000    0.000000

patient_id           76230      93c14      96adf      a2849      b0455  \
mean_HR   count   4.000000  46.000000  86.000000  61.000000  10.000000
          mean   60.556002  58.189086  57.898670  63.212748  57.370850
          std     1.884970   1.589265   4.187333   2.433823   1.376896
          min    57.875912  55.368421  51.855590  57.936685  54.893855
          25%    59.923145  56.929255  55.288946  61.189286  56.500119
...                    ...        ...        ...        ...        ...
agitation min     0.000000   0.000000   0.000000   0.000000   0.000000
          25%     0.000000   0.000000   0.000000   0.000000   0.000000
          50%     0.000000   0.000000   0.000000   0.000000   0.000000
          75%     0.000000   0.000000   0.000000   0.000000   0.000000
          max     0.000000   1.000000   0.000000   1.000000   0.000000

patient_id           c55f8      c5785      c8574      d7a46      e2472  \
mean_HR   count  86.000000  68.000000  55.000000  18.000000  30.000000
          mean   57.771079  61.115927  54.383433  64.409600  51.186421
          std     2.893896   7.403699   2.103083   1.630742   4.166527
          min    51.417749  46.063107  50.891841  62.190045  44.707826
          25%    55.908782  55.159318  53.008034  63.540875  48.706973
...                    ...        ...        ...        ...        ...
agitation min     0.000000   0.000000   0.000000   0.000000   0.000000
          25%     0.000000   0.000000   0.000000   0.000000   0.000000
          50%     0.000000   0.000000   0.000000   0.000000   0.000000
          75%     0.000000   0.000000   0.000000   0.000000   0.000000
          max     0.000000   0.000000   0.000000   0.000000   0.000000

patient_id           ec812      f220c
mean_HR   count  84.000000  72.000000
          mean   63.580614  68.638542
          std     4.659712   3.297159
          min    58.199627  62.522968
          25%    60.798882  66.222097
...                    ...        ...
agitation min     0.000000   0.000000
          25%     0.000000   0.000000
          50%     0.000000   0.000000
          75%     0.000000   0.000000
          max     1.000000   0.000000

[88 rows x 17 columns]

In [12]:
df.loc[:,~df.columns.isin(['agitation','window_start'])].groupby('patient_id').describe().T

patient_id                0f352      16f4b       1fbe4      30a32       55cd4  \
mean_HR        count   7.000000  75.000000   56.000000  67.000000  101.000000
               mean   63.871361  68.679046   53.560003  64.163753   64.968206
               std     3.394559   5.724923    2.359509   3.288711    4.666326
               min    58.366667  54.222973   49.962617  57.149188   55.728155
               25%    61.905581  65.995963   51.661086  61.805034   61.316129
...                         ...        ...         ...        ...         ...
snoring_counts min     0.000000   0.000000    0.000000   0.000000    0.000000
               25%     0.000000   0.000000   50.250000   0.000000    0.000000
               50%     0.000000   0.000000   96.500000   0.000000    0.000000
               75%     0.000000   0.000000  130.500000   0.000000    0.000000
               max    80.000000   4.000000  291.000000  10.000000   22.000000

patient_id                76230       93c14      96adf       a2849      b0455  \
mean_HR        count   4.000000   46.000000  86.000000   61.000000  10.000000
               mean   60.556002   58.189086  57.898670   63.212748  57.370850
               std     1.884970    1.589265   4.187333    2.433823   1.376896
               min    57.875912   55.368421  51.855590   57.936685  54.893855
               25%    59.923145   56.929255  55.288946   61.189286  56.500119
...                         ...         ...        ...         ...        ...
snoring_counts min    15.000000    3.000000   0.000000    0.000000   2.000000
               25%    25.500000   32.750000   0.000000   20.000000  10.500000
               50%    56.000000   51.500000   0.000000   41.000000  18.000000
               75%    85.250000   81.000000  10.500000   70.000000  21.750000
               max    92.000000  153.000000  51.000000  127.000000  44.000000

patient_id                c55f8       c5785      c8574      d7a46      e2472  \
mean_HR        count  86.000000   68.000000  55.000000  18.000000  30.000000
               mean   57.771079   61.115927  54.383433  64.409600  51.186421
               std     2.893896    7.403699   2.103083   1.630742   4.166527
               min    51.417749   46.063107  50.891841  62.190045  44.707826
               25%    55.908782   55.159318  53.008034  63.540875  48.706973
...                         ...         ...        ...        ...        ...
snoring_counts min     0.000000    0.000000   0.000000   0.000000   0.000000
               25%     1.500000    0.000000   0.000000   0.000000  17.750000
               50%     8.000000    3.000000   0.000000   0.000000  31.500000
               75%    17.750000   15.250000   4.000000   3.000000  40.750000
               max    64.000000  181.000000  26.000000  17.000000  82.000000

patient_id                ec812      f220c
mean_HR        count  84.000000  72.000000
               mean   63.580614  68.638542
               std     4.659712   3.297159
               min    58.199627  62.522968
               25%    60.798882  66.222097
...                         ...        ...
snoring_counts min     0.000000   0.000000
               25%     0.000000   0.000000
               50%     0.000000   0.000000
               75%     0.000000   0.000000
               max    11.000000   0.000000

[80 rows x 17 columns]

926, 24 agitation and the rest non-agitated

Sleep Variables: 
patient_id	
window_start	
mean_HR	HR_var	
mean_RR	RR_var	
WASO	
SOL	
TIB	
TST	
SE	
snoring_counts	
agitation